
FROM nvidia/cuda:12.1.0-runtime-ubuntu22.04

WORKDIR /app
COPY . .

RUN apt-get update && apt-get install -y build-essential  && pip install --upgrade pip  && pip install -r requirements.txt

CMD ["uvicorn","api.main:app","--host","0.0.0.0","--port","8000"]
