FROM python:3.10-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=1

EXPOSE 8501

CMD ["streamlit", "run", "movie_factory/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
